language: python

python:
  - 3.7

git:
  submodules: false

before_install:
  # cannot use SSH to fetch submodule
  - sed -i 's#git@github.com:#https://github.com/#' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script:
  - qgis-plugin-ci --version

deploy:
  provider: script
  script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --create-plugin-repo --osgeo-username ${OSGEO_USERNAME} --osgeo-password ${OSGEO_PASSWORD}
  on:
    tags: true
